### PR TITLE
Expiration indicator and BCC compatibility

### PR DESCRIPTION
**Pull request by Road-block**
add an indicator to expiration time if mail will bounce back to sender or be destroyed
make some of the auction house substitutions locale independent
avoid hardcoding the addon name in addon declaration and locale
test that it works for burning crusade classic and add multitoc

### CODE REVIEW

**Comment by Road-block** [comment]
Pull request can be tested in packaged form at [this temporary release](https://github.com/Road-block/GnomishInboxShrinker/releases/latest).

**Comment by glassleo** [comment]
Thanks a lot for the pull request! I've ended up changing the appearance a bit so that it only shows a warning triangle if the mail will be deleted on expiration (no icon is shown if it will bounce).

I've also changed the way money (gold/silver/copper) looks in 9.2.1, would be thankful if you could test it on TBCC and see if the coin textures are available. Otherwise we'll have to add a workaround. I only have the retail client installed atm.

**Comment by Road-block** [comment]
Loaded the latest version, can't see any issues on TBC.
Money textures work fine.

**Comment by glassleo** [comment]
Great, thanks for checking!

**Comment by Road-block** [comment]
Hey, since I kinda have your 👂🏻 in this closed pull request.

This is by no means a big deal but since this is a tekkub (originally) addon he would have something to say about the GSC function 😝 

Functions are amongst the most "expensive" things in Lua and this is running CreateAtlasMarkup every time it's invoked to produce what is essentially fixed strings that never change.

It would be better if they were created once outside of the function and simply reused.

```lua
local copper_coin = CreateAtlasMarkup("auctionhouse-icon-coin-copper")
local silver_coin = CreateAtlasMarkup("auctionhouse-icon-coin-silver")
local gold_coin = CreateAtlasMarkup("auctionhouse-icon-coin-gold")
local function GSC(money)
  -- use the predefined *_coin strings
end
```
Something like that. I have another small change to suggest but that's more of a feature / QoL request not optimization so I'll use a separate comment.


**Edit:** Superseded by the last comment about using GetMoneyString, I'd go with that and get rid of the custom code.

**Comment by Road-block** [comment]
So on AH mules and similar the same thing that is the biggest improvement for Inbox (scrollable, mouse-scrollable) is also a problem because it's hard to see which ones you've already mouse-overed when you scroll.

You can always use the up/down buttons on the scrollbar to scroll by a fixed amount but I thought it would be convenient to have a visual indicator of your current offset for you when you're using the scrollwheel to scroll.

So I added the scroll offset to the scrollbar thumb
image

The code to do this is in 2 places.
In the embedded tekScrollbar.lua file the section starting [line 62](https://github.com/glassleo/GnomishInboxShrinker/blob/4e509b796330d52482552f9b1fb67bfd7f1e09df/GnomishInboxShrinker/tekScrollBar.lua#L62) changed to
```lua
f:SetThumbTexture("Interface\\Buttons\\UI-ScrollBar-Knob")
local thumb = f:GetThumbTexture()
thumb:SetWidth(16) thumb:SetHeight(24)
thumb:SetTexCoord(1/4, 3/4, 1/8, 7/8)
local ofs = f:CreateFontString(nil, "OVERLAY", "GameFontWhiteTiny")
local font,h = ofs:GetFont(); h = floor(h+0.5)
ofs:SetFont(font,h,"OUTLINE")
ofs:SetAllPoints(thumb)
f.offset = ofs
```

In GnomishInboxShrinker.lua updating the [BetterInbox:UpdateInboxScroll()](https://github.com/glassleo/GnomishInboxShrinker/blob/4e509b796330d52482552f9b1fb67bfd7f1e09df/GnomishInboxShrinker/GnomishInboxShrinker.lua#L153) to
```lua
function BetterInbox:UpdateInboxScroll()
	if self.scroll then
		local numitems = GetInboxNumItems()
		local offset = self.scroll:GetValue()

		self.scroll:SetMinMaxValues(0, math.max(0, numitems-NUMROWS))

		for i,row in pairs(rows) do
			local index = i + offset
			if index <= numitems then row:Update(index)
			else row:Hide() end
		end
		self.scroll.offset:SetText(format("%02d",tostring(offset)))
	end
end
```

**Comment by Road-block** [comment]
Just to add that the user made `function GSC` in GnomishInboxShrinker.lua can be entirely replaced by the built-in utility function `GetMoneyString` It would be a 1-1 replacement and if you wanted to preserve your FormatLargeNumbers functionality you'd simply call it like this.

```lua
GetMoneyString(amount,true) -- 2nd parameter controls if we're using FormatLargeNumbers or not
```
Simplest way to do it would be to just get rid of everything in GSC and define it like this
```lua
local function GSC(money)
  if not money then return end
  money = GetMoneyString(money,true)
  return money
end
```
Then no need to run around and replace all the GSC calls in other places.

**Comment by glassleo** [comment]
> Hey, since I kinda have your 👂🏻 in this closed pull request.
> 
> This is by no means a big deal but since this is a tekkub (originally) addon he would have something to say about the GSC function 😝
> 
> Functions are amongst the most "expensive" things in Lua and this is running CreateAtlasMarkup every time it's invoked to produce what is essentially fixed strings that never change.
> 
> It would be better if they were created once outside of the function and simply reused.
> 
> ```lua
> local copper_coin = CreateAtlasMarkup("auctionhouse-icon-coin-copper")
> local silver_coin = CreateAtlasMarkup("auctionhouse-icon-coin-silver")
> local gold_coin = CreateAtlasMarkup("auctionhouse-icon-coin-gold")
> local function GSC(money)
>   -- use the predefined *_coin strings
> end
> ```
> 
> Something like that. I have another small change to suggest but that's more of a feature / QoL request not optimization so I'll use a separate comment.
> 
> **Edit:** Superseded by the last comment about using GetMoneyString, I'd go with that and get rid of the custom code.

I don't think it matters much for modern computers but sure, let's implement this optimization.

**Comment by glassleo** [comment]
2 reasons why I didn't go with ``GetMoneyString``:

1. It uses the old coin textures for some reason which looks bad when mixed with the new coin textures used elsewhere in the mail frame
2. My function saves a lot of space in the inbox list - I don't need to know how many silver and copper I was sent when I sold an auction for 100,000 gold. I'll do the optimizations you first suggested so that ``CreateAtlasMarkup`` isn't called so many times though. If you have a better solution I'm all ears!

On that note, maybe it's time for some user options so you can choose if you want the old style G.S.C format or the new and fancy texture version. I'd also like to add an option to condense the gold amounts even further (``10,000`` --> ``10K``).

**Comment by glassleo** [comment]
> So on AH mules and similar the same thing that is the biggest improvement for Inbox (scrollable, mouse-scrollable) is also a problem because it's hard to see which ones you've already mouse-overed when you scroll.
> 
> You can always use the up/down buttons on the scrollbar to scroll by a fixed amount but I thought it would be convenient to have a visual indicator of your current offset for you when you're using the scrollwheel to scroll.
> 
> So I added the scroll offset to the scrollbar thumb image
> 
> The code to do this is in 2 places. In the embedded tekScrollbar.lua file the section starting [line 62](https://github.com/glassleo/GnomishInboxShrinker/blob/4e509b796330d52482552f9b1fb67bfd7f1e09df/GnomishInboxShrinker/tekScrollBar.lua#L62) changed to
> 
> ```lua
> f:SetThumbTexture("Interface\\Buttons\\UI-ScrollBar-Knob")
> local thumb = f:GetThumbTexture()
> thumb:SetWidth(16) thumb:SetHeight(24)
> thumb:SetTexCoord(1/4, 3/4, 1/8, 7/8)
> local ofs = f:CreateFontString(nil, "OVERLAY", "GameFontWhiteTiny")
> local font,h = ofs:GetFont(); h = floor(h+0.5)
> ofs:SetFont(font,h,"OUTLINE")
> ofs:SetAllPoints(thumb)
> f.offset = ofs
> ```
> 
> In GnomishInboxShrinker.lua updating the [BetterInbox:UpdateInboxScroll()](https://github.com/glassleo/GnomishInboxShrinker/blob/4e509b796330d52482552f9b1fb67bfd7f1e09df/GnomishInboxShrinker/GnomishInboxShrinker.lua#L153) to
> 
> ```lua
> function BetterInbox:UpdateInboxScroll()
> 	if self.scroll then
> 		local numitems = GetInboxNumItems()
> 		local offset = self.scroll:GetValue()
> 
> 		self.scroll:SetMinMaxValues(0, math.max(0, numitems-NUMROWS))
> 
> 		for i,row in pairs(rows) do
> 			local index = i + offset
> 			if index <= numitems then row:Update(index)
> 			else row:Hide() end
> 		end
> 		self.scroll.offset:SetText(format("%02d",tostring(offset)))
> 	end
> end
> ```

I'm open to implementing this as a user option that is turned off by default (I wouldn't personally use it - I think it clutters the UI a bit) but we'd need to implement an options UI and some saved variables first.

Open a new issue/pull request if you want to continue this discussion.

**Pull request merged**
